camera_matrix:
- - 1237.0997928450688
  - 0.0
  - 944.2815409963811
- - 0.0
  - 1231.892449782019
  - 546.0240890545015
- - 0.0
  - 0.0
  - 1.0
camera_resolution:
- 1920
- 1080
distort_coefs:
- 0.08005278116109732
- -0.039205541800382986
- -0.009012010811878567
- -0.005724564424245133
- -0.2975870717810594
running_average_alpha: 0.75
segmentation_classes:
- input_colors:
  - max:
    - 103.0
    - 173.39999999999998
    - 254.99999999999997
    min:
    - 94.5
    - 0.0
    - 86.69999999999999
    name: blue
  kernel_size: 25
  morph_op: close
  name: obstacle
  output_color: 85
- input_colors:
  - max:
    - 32.0
    - 196.35
    - 254.99999999999997
    min:
    - 5.0
    - 107.1
    - 117.3
    name: orange
  - max:
    - 180.0
    - 254.99999999999997
    - 254.99999999999997
    min:
    - 115.5
    - 25.5
    - 165.75
    name: red
  kernel_size: 0
  morph_op: open
  name: arm
  output_color: 255
ws_corners:
  bottom_left:
  - !!python/object/apply:numpy.core.multiarray.scalar
    - &id001 !!python/object/apply:numpy.dtype
      args:
      - f8
      - false
      - true
      state: !!python/tuple
      - 3
      - <
      - null
      - null
      - null
      - -1
      - -1
      - 0
    - !!binary |
      /6JUqDiKkUA=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      VRhhoAtvjEA=
  bottom_right:
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      VVF8X72wkUA=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      d+/tyVVCUEA=
  top_left:
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      oIwZKZCDgUA=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      HLaQIFAhjEA=
  top_right:
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      wlNqpOMngkA=
  - !!python/object/apply:numpy.core.multiarray.scalar
    - *id001
    - !!binary |
      R4iP57XAREA=
